x-common: &common
  build:
    context: .
    args:
      WWWUSER: ${WWWUSER:-1000}
      WWWGROUP: ${WWWGROUP:-1000}
  env_file:
    - .env
  volumes:
    - .:/app
    - ./cover:/app/cover
    - ./downloads:/app/downloads
    - ./epub:/app/epub
    - ./logs:/app/logs
  environment:
    - PYTHONDONTWRITEBYTECODE=1
    - PYTHONUNBUFFERED=1
    - TEMPORAL_HOST=temporal
    - TEMPORAL_PORT=7233
    - PYTHONPATH=/app
  user: "${WWWUSER}:${WWWGROUP}"
  networks:
    - dev_tools

services:
  app:
    <<: *common
    ports:
      - "${APP_PORT:-80}:80"
    command: uvicorn src.api:app --host 0.0.0.0 --port 80 --reload

  worker:
    <<: *common
    command: python -m src.workers.worker
    depends_on:
      - app

networks:
  dev_tools:
    external: true
